version: "3.8"

services:
  app:
    container_name: smartbrain-front-dev
    image: smartbrain-front-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 3001:3001
