version: "3.8"

services:
  app:
    container_name: app-dev
    image: smart-brain-app-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 3001:3001
